# Dockerfile.nginx
FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

WORKDIR /var/www

# Permissão ao Nginx para acessar arquivos
RUN chown -R nginx:nginx /var/www

CMD ["nginx", "-g", "daemon off;"]
